CREATE TABLE IF NOT EXISTS Effects
(
  effect_id INTEGER NOT NULL PRIMARY KEY,
  effect_name VARCHAR(100) NOT NULL,
  effect_type VARCHAR(50) NOT NULL,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Dungeons
(
  dungeon_id INTEGER NOT NULL PRIMARY KEY,
  dungeon_name VARCHAR(100) NOT NULL,
  required_level INTEGER DEFAULT 1,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Monsters
(
  monster_id INTEGER NOT NULL PRIMARY KEY,
  monster_name VARCHAR(100) NOT NULL,
  monster_hp FLOAT NOT NULL,
  monster_attack FLOAT NOT NULL,
  monster_exp INTEGER NOT NULL,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Dungeon_Monsters
(
  dungeon_monster_id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  dungeon_id INTEGER,
  monster_id INTEGER,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  FOREIGN KEY (dungeon_id) REFERENCES Dungeons(dungeon_id),
  FOREIGN KEY (monster_id) REFERENCES Monsters(monster_id)
);



CREATE TABLE IF NOT EXISTS Shops
(
  shop_id INTEGER AUTO_INCREMENT PRIMARY KEY,
  shop_name VARCHAR(100) UNIQUE NOT NULL,
  shop_location VARCHAR(100),

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Items
(
  item_id INTEGER AUTO_INCREMENT PRIMARY KEY,
  item_name VARCHAR(100) NOT NULL,
  item_description TEXT,
  item_type VARCHAR(50),
  item_rarity VARCHAR(50),
  item_effect_id INTEGER DEFAULT 1,
  item_hp FLOAT NOT NULL,
  item_mp FLOAT NOT NULL,
  item_attack FLOAT NOT NULL,
  item_defense FLOAT NOT NULL,
  item_magic FLOAT NOT NULL,
  item_speed FLOAT NOT NULL,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Shop_Items
(
  shop_item_id INTEGER AUTO_INCREMENT PRIMARY KEY,
  shop_id INTEGER,
  item_id INTEGER,
  price INTEGER NOT NULL,
  stock INTEGER DEFAULT 0,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  FOREIGN KEY (shop_id) REFERENCES Shops(shop_id),
  FOREIGN KEY (item_id) REFERENCES Items(item_id)
);

CREATE TABLE IF NOT EXISTS Levels
(
  level_id INTEGER AUTO_INCREMENT PRIMARY KEY,
  required_exp INTEGER NOT NULL,
  hp FLOAT NOT NULL,
  mp FLOAT NOT NULL,
  attack FLOAT NOT NULL,
  defense FLOAT NOT NULL,
  magic FLOAT NOT NULL,
  speed FLOAT NOT NULL,
  skill_point INTEGER NOT NULL,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

//데이터 삽입

//레벨 데이터 삽입
INSERT INTO Levels (level_id, required_exp, hp, mp, attack, defense, magic, speed, skill_point) VALUES 
(NULL, 0, 0, 0, 0, 0, 0, 0, 0),
(NULL, 100, 10, 10, 2, 2, 2, 2, 1),
(NULL, 250, 10, 10, 2, 2, 2, 2, 1),
(NULL, 450, 15, 15, 3, 3, 3, 3, 1),
(NULL, 700, 15, 15, 3, 3, 3, 3, 2),
(NULL, 1000, 20, 20, 4, 4, 4, 4, 1),
(NULL, 1350, 25, 25, 4, 4, 4, 4, 1),
(NULL, 1750, 25, 25, 5, 5, 5, 5, 1),
(NULL, 2200, 30, 30, 5, 5, 5, 5, 1),
(NULL, 2700, 30, 30, 6, 6, 6, 6, 2),
(NULL, 3250, 35, 35, 6, 6, 6, 6, 1),
(NULL, 3850, 35, 35, 7, 7, 7, 7, 1),
(NULL, 4500, 40, 40, 7, 7, 7, 7, 1),
(NULL, 5200, 40, 40, 8, 8, 8, 8, 1),
(NULL, 5950, 45, 45, 8, 8, 8, 8, 2),
(NULL, 6750, 45, 45, 9, 9, 9, 9, 1),
(NULL, 7600, 50, 50, 9, 9, 9, 9, 1),
(NULL, 8500, 50, 50, 10, 10, 10, 10, 1),
(NULL, 9450, 60, 60, 10, 10, 10, 10, 1),
(NULL, 10450, 60, 60, 12, 12, 12, 12, 2);