CREATE TABLE IF NOT EXISTS Jobs
(
  job_id INTEGER NOT NULL PRIMARY KEY,
  job_name VARCHAR(50) NOT NULL UNIQUE,
  base_hp FLOAT NOT NULL,
  base_mp FLOAT NOT NULL,
  base_attack FLOAT NOT NULL,
  base_defense FLOAT NOT NULL,
  base_magic FLOAT NOT NULL,
  base_speed FLOAT NOT NULL,
  base_effect INTEGER NOT NULL,
  single_effect INTEGER NOT NULL,
  wide_effect INTEGER NOT NULL,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Users
(
  user_id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Characters
(
  character_id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INTEGER,
  character_name VARCHAR(50) NOT NULL,
  character_level INTEGER NOT NULL DEFAULT 1,
  experience INTEGER NOT NULL,
  job_id INTEGER,
  job_name VARCHAR(50) NOT NULL,
  cur_hp FLOAT NOT NULL,
  max_hp FLOAT NOT NULL,
  cur_mp FLOAT NOT NULL,
  max_mp FLOAT NOT NULL,
  attack FLOAT NOT NULL,
  defense FLOAT NOT NULL,
  magic FLOAT NOT NULL,
  speed FLOAT NOT NULL,
  
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  FOREIGN KEY (user_id) REFERENCES Users(user_id),
  FOREIGN KEY (job_id) REFERENCES Jobs(job_id)
);

CREATE TABLE IF NOT EXISTS Character_Items
(
  character_item_id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  character_id INTEGER,
  item_id INTEGER NOT NULL,
  quantity INTEGER DEFAULT 1,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  FOREIGN KEY (character_id) REFERENCES Characters(character_id)
);