export const packetNames = {
  response: {
    S_Enter: 'response.S_Enter',
    S_Spawn: 'response.S_Spawn',
    S_Move: 'response.S_Move',
    S_Animation: 'response.S_Animation',
    S_Chat: 'response.S_Chat',
    S_EnterDungeon: 'response.S_EnterDungeon',
    S_Despawn: 'response.S_Despawn',
    S_Register: 'response.S_Register',
    S_LogIn: 'response.S_LogIn',
    S_LeaveDungeon: 'response.S_LeaveDungeon',
    S_ScreenText: 'response.S_ScreenText',
    S_ScreenDone: 'response.S_ScreenDone',
    S_BattleLog: 'response.S_BattleLog',
    S_SetPlayerHp: 'response.S_SetPlayerHp',
    S_SetPlayerMp: 'response.S_SetPlayerMp',
    S_SetMonsterHp: 'response.S_SetMonsterHp',
    S_PlayerAction: 'response.S_PlayerAction',
    S_MonsterAction: 'response.S_MonsterAction',
    S_EnterHatchery: 'response.S_EnterHatchery',
    S_SpawnPlayerHatchery: 'response.S_SpawnPlayerHatchery',
    S_MoveAtHachery: 'response.S_MoveAtHatchery',
    S_SetHatcheryBossHp: 'response.S_SetHatcheryBossHp',
    S_BuyItem: 'response.S_BuyItem',
    S_SellItem: 'response.S_SellItem',
  },
  town: {
    C_Enter: 'town.C_Enter',
    C_Move: 'town.C_Move',
    C_Animation: 'town.C_Animation',
    C_Chat: 'town.C_Chat',
    C_EnterDungeon: 'town.C_EnterDungeon',
    C_Register: 'town.C_Register',
    C_LogIn: 'town.C_LogIn',
    C_EnterHatchery: 'town.C_EnterHatchery',
    C_BuyItem: 'town.C_BuyItem',
    C_SellItem: 'town.C_SellItem',
  },
  battle: {
    C_PlayerResponse: 'battle.C_PlayerResponse',
  },
  hatchery: {
    C_MoveAtHatchery: 'hatchery.C_MoveAtHatchery',
    C_AttackBoss: 'hatchery.C_AttackBoss',
  },
  custom: {
    PlayerInfo: 'custom.PlayerInfo',
    TransformInfo: 'custom.TransformInfo',
    StatInfo: 'custom.StatInfo',
    ScreenText: 'custom.ScreenText',
    ScreenTextAlignment: 'custom.ScreenTextAlignment',
    Color: 'custom.Color',
    DungeonInfo: 'custom.DungeonInfo',
    MonsterStatus: 'custom.MonsterStatus',
    ActionSet: 'custom.ActionSet',
    PlayerStatus: 'custom.PlayerStatus',
    BattleLog: 'custom.BattleLog',
    BtnInfo: 'custom.BtnInfo',
    ItemInfo: 'custom.ItemInfo'
  },
};
