export const MAX_PLAYERS = 4;
export const BOSS_ID = 2028;
export const BOSS_INIT_TRANSFORM = { posX: -3.5, posY: -19.5, posZ: -315.0, rot: 0 };
export const BOSS_TARGET_INTERVAL_ID = 'bossTargetPlayer';
export const BOSS_TARGET_INTERVAL = 500;
export const BOSS_ATTACK_RANGE = 4;
export const DROP_ITEMS_QUANTITY = 6;
export const BOSS_ATTACK_SPEED = 3000;
export const HATCHERY_SPAWN_AREA_POSITION = { x: -3.55, y: -14.8, z: -267.3 };
